# Generated by Django 4.2.18 on 2026-02-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrutor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rg', models.CharField(help_text='Informe o RG do instrutor', max_length=15)),
                ('nome', models.CharField(help_text='Informe o nome do instrutor', max_length=70)),
                ('data_Nascimento', models.DateField(blank=True, help_text='Informe a data de nascimento do instrutor', null=True)),
                ('telefone', models.CharField(help_text='Informe o telefone do instrutor', max_length=9)),
                ('ddd', models.CharField(help_text='Informe o DDD do telefone do instrutor', max_length=3)),
                ('codigo_titulo', models.IntegerField(help_text='Informe o código do título do instrutor')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
