# Generated by Django 4.2.18 on 2026-02-26 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instrutor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='instrutor',
            options={'ordering': ['id'], 'verbose_name': 'Instrutor', 'verbose_name_plural': 'Instrutores'},
        ),
        migrations.RenameField(
            model_name='instrutor',
            old_name='data_Nascimento',
            new_name='data_nascimento',
        ),
    ]
