# Generated by Django 4.2.18 on 2026-01-30 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoDeAtividade',
            fields=[
                ('codigo', models.IntegerField(help_text='Código do Tipo de atividade', primary_key=True, serialize=False)),
                ('descricao', models.CharField(help_text='Informe a descrição do Tipo de atividade', max_length=70)),
            ],
        ),
    ]
