# Generated by Django 4.2.18 on 2026-02-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('matricula', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(help_text='Informe o nome do aluno', max_length=70)),
                ('data_inicial', models.DateField(blank=True, help_text='Informe a data inicial de matrícula do aluno', null=True)),
                ('data_final', models.DateField(blank=True, help_text='Informe a data de final de matrícula do aluno', null=True)),
            ],
            options={
                'verbose_name': 'Aluno',
                'verbose_name_plural': 'Alunos',
                'ordering': ['matricula'],
            },
        ),
    ]
