# Generated by Django 4.2.18 on 2026-02-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('titulo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulo',
            name='descricao',
            field=models.CharField(help_text='Informe a descrição do Título', max_length=70),
        ),
    ]
